/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

import com.mycompany.dormnew.GUI.Admin;

/**
 *
 * @author tee
 */
public class AdminLogin extends javax.swing.JFrame {

    private static final String FILE_DIR = "./File/";

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AdminLogin.class.getName());

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BrookingDorm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        Showpassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(204, 255, 204));
        Background.setForeground(new java.awt.Color(255, 255, 255));

        BrookingDorm.setFont(new java.awt.Font("EucrosiaUPC", 1, 48)); // NOI18N
        BrookingDorm.setText("BrookingDorm Appication");

        jLabel1.setFont(new java.awt.Font("EucrosiaUPC", 1, 42)); // NOI18N
        jLabel1.setText("Admin Login     ");

        t1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t1.setToolTipText("");
        t1.setActionCommand("<Not Set>");
        t1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        p1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        BtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        Showpassword.setBackground(new java.awt.Color(255, 96, 161));
        Showpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Showpassword.setText("ShowPassword");
        Showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
                BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(189, 189, 189)
                                                .addComponent(jLabel1))
                                        .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(192, 192, 192)
                                                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addGroup(BackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(BrookingDorm)
                                                        .addGroup(BackgroundLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(t1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 379,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(p1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 379,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Showpassword)))))
                                .addContainerGap(77, Short.MAX_VALUE)));
        BackgroundLayout.setVerticalGroup(
                BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(BrookingDorm)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Showpassword)
                                .addGap(65, 65, 65)
                                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_p1ActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnLoginActionPerformed
        String AdminUsername = t1.getText().trim(); // tostring and delete Space
        String AdminPassword = new String(p1.getPassword());

        if (AdminUsername.isEmpty() || AdminPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete all fields.", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (AdminPassword.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must at least 8 characters.", "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 🔹 Path ไฟล์ CSV
        String filePath = FILE_DIR + "/admin_password.csv";

        boolean isLoginSuccess = false;

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 2) {
                    String username = data[0].trim();
                    String password = data[1].trim();

                    // 🔹 ตรวจสอบ username และ password
                    if (AdminUsername.equals(username) && AdminPassword.equals(password)) {
                        isLoginSuccess = true;
                        break;
                    }
                }
            }
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading admin file:\n" + e.getMessage(), "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (isLoginSuccess) {
            JOptionPane.showMessageDialog(this, "Login Successful!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            Admin adminPage = new Admin(); // <<-- class ชื่อว่า Admin ใช่ไหม
            adminPage.setVisible(true);
            this.dispose(); // ปิดหน้าล็อกอิน

        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_BtnLoginActionPerformed

    private void ShowpasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ShowpasswordActionPerformed
        if (Showpassword.isSelected()) {
            p1.setEchoChar('\u0000'); // password show
        } else {
            p1.setEchoChar('*'); // password hide
        }
    }// GEN-LAST:event_ShowpasswordActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BrookingDorm;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JCheckBox Showpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
